# Generated by Django 3.0.3 on 2020-02-13 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, verbose_name='生日')),
                ('avartar', models.ImageField(default='default_avartar.png', upload_to='avartars', verbose_name='头像')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='常住地')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '注册用户',
            },
        ),
    ]
